# Generated by Django 4.2.3 on 2023-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('market_cap', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
            ],
        ),
    ]
